author: Tobe O <thosakwe@gmail.com>
description: Material toolbar for Angular2.
homepage: https://github.com/thosakwe/material_toolbar
name: material_toolbar
version: 2.0.2
environment:
  sdk: ">=1.23.0-beta"
dependencies: 
  angular2: ">=3.0.0-beta <4.0.0"
  angular_components: ">=0.5.0-beta <2.0.0"
dev_dependencies:
  angel_framework: ^1.0.0
  angel_static: ^1.0.0
  browser: ^0.10.0
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart